// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package batch

import (
	builders "github.com/kubernetes-incubator/apiserver-builder/pkg/builders"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	reflect "reflect"
)

func init() {
	SchemeBuilder.Register(RegisterDeepCopies)
}

// RegisterDeepCopies adds deep-copy functions to the given scheme. Public
// to allow building arbitrary schemes.
func RegisterDeepCopies(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedDeepCopyFuncs(
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_batch_Network, InType: reflect.TypeOf(&Network{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_batch_NetworkList, InType: reflect.TypeOf(&NetworkList{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_batch_NetworkSpec, InType: reflect.TypeOf(&NetworkSpec{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_batch_NetworkStatus, InType: reflect.TypeOf(&NetworkStatus{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_batch_NetworkStatusStrategy, InType: reflect.TypeOf(&NetworkStatusStrategy{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_batch_NetworkStrategy, InType: reflect.TypeOf(&NetworkStrategy{})},
	)
}

// DeepCopy_batch_Network is an autogenerated deepcopy function.
func DeepCopy_batch_Network(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*Network)
		out := out.(*Network)
		*out = *in
		if newVal, err := c.DeepCopy(&in.ObjectMeta); err != nil {
			return err
		} else {
			out.ObjectMeta = *newVal.(*v1.ObjectMeta)
		}
		return nil
	}
}

// DeepCopy_batch_NetworkList is an autogenerated deepcopy function.
func DeepCopy_batch_NetworkList(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*NetworkList)
		out := out.(*NetworkList)
		*out = *in
		if in.Items != nil {
			in, out := &in.Items, &out.Items
			*out = make([]Network, len(*in))
			for i := range *in {
				if err := DeepCopy_batch_Network(&(*in)[i], &(*out)[i], c); err != nil {
					return err
				}
			}
		}
		return nil
	}
}

// DeepCopy_batch_NetworkSpec is an autogenerated deepcopy function.
func DeepCopy_batch_NetworkSpec(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*NetworkSpec)
		out := out.(*NetworkSpec)
		*out = *in
		return nil
	}
}

// DeepCopy_batch_NetworkStatus is an autogenerated deepcopy function.
func DeepCopy_batch_NetworkStatus(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*NetworkStatus)
		out := out.(*NetworkStatus)
		*out = *in
		return nil
	}
}

// DeepCopy_batch_NetworkStatusStrategy is an autogenerated deepcopy function.
func DeepCopy_batch_NetworkStatusStrategy(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*NetworkStatusStrategy)
		out := out.(*NetworkStatusStrategy)
		*out = *in
		if newVal, err := c.DeepCopy(&in.DefaultStatusStorageStrategy); err != nil {
			return err
		} else {
			out.DefaultStatusStorageStrategy = *newVal.(*builders.DefaultStatusStorageStrategy)
		}
		return nil
	}
}

// DeepCopy_batch_NetworkStrategy is an autogenerated deepcopy function.
func DeepCopy_batch_NetworkStrategy(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*NetworkStrategy)
		out := out.(*NetworkStrategy)
		*out = *in
		if newVal, err := c.DeepCopy(&in.DefaultStorageStrategy); err != nil {
			return err
		} else {
			out.DefaultStorageStrategy = *newVal.(*builders.DefaultStorageStrategy)
		}
		return nil
	}
}
