/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package network

import (
	"github.com/golang/glog"
	"github.com/heartlock/apiserver-demo/pkg/controller/sharedinformers"
	"github.com/kubernetes-incubator/apiserver-builder/pkg/controller"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/cache"
	"k8s.io/client-go/util/workqueue"
)

// NetworkController implements the controller.NetworkController interface
type NetworkController struct {
	queue *controller.QueueWorker

	// Handles messages
	controller *NetworkControllerImpl

	Name string

	BeforeReconcile func(key string)
	AfterReconcile  func(key string, err error)
}

// NewController returns a new NetworkController for responding to Network events
func NewNetworkController(config *rest.Config, si *sharedinformers.SharedInformers) *NetworkController {
	q := workqueue.NewNamedRateLimitingQueue(workqueue.DefaultControllerRateLimiter(), "Network")

	// For non-generated code to add events
	uc := &NetworkControllerImpl{}
	uc.Init(config, si, q)

	queue := &controller.QueueWorker{q, 10, "Network", nil}
	c := &NetworkController{queue, uc, "Network", nil, nil}
	queue.Reconcile = c.reconcile
	return c
}

func (c *NetworkController) GetName() string {
	return c.Name
}

func (c *NetworkController) reconcile(key string) (err error) {
	var namespace, name string

	if c.BeforeReconcile != nil {
		c.BeforeReconcile(key)
	}
	if c.AfterReconcile != nil {
		// Wrap in a function so err is evaluated after it is set
		defer func() { c.AfterReconcile(key, err) }()
	}

	namespace, name, err = cache.SplitMetaNamespaceKey(key)
	if err != nil {
		return
	}

	u, err := c.controller.Get(namespace, name)
	if errors.IsNotFound(err) {
		glog.Infof("Not doing work for Network %v because it has been deleted", key)
		// Set error so it is picked up by AfterReconcile and the return function
		err = nil
		return
	}
	if err != nil {
		glog.Errorf("Unable to retrieve Network %v from store: %v", key, err)
		return
	}

	// Set error so it is picked up by AfterReconcile and the return function
	err = c.controller.Reconcile(u)

	return
}

func (c *NetworkController) Run(stopCh <-chan struct{}) {
	c.queue.Run(stopCh)
}
